# Generated by Django 4.2.2 on 2023-08-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=20)),
                ('examlink', models.CharField(max_length=100)),
                ('dateofexam', models.DateField()),
                ('examtime', models.TimeField()),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
    ]
