# Generated by Django 3.2.18 on 2023-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examstudent',
            name='examid',
            field=models.CharField(max_length=20),
        ),
    ]
