# Generated by Django 3.2.18 on 2023-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=5)),
                ('fees', models.ImageField(max_length=5, upload_to='')),
                ('duedate', models.DateField()),
                ('paiddate', models.DateField()),
                ('paidamount', models.IntegerField(max_length=5)),
            ],
        ),
    ]
