# Generated by Django 3.2.18 on 2023-07-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20230730_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fees',
            name='paidamount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='paiddate',
            field=models.DateField(blank=True),
        ),
    ]
