# Generated by Django 3.2.18 on 2023-07-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20230730_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='paidamount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='paiddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
