# Generated by Django 3.2.18 on 2023-07-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20230730_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('batchtime', models.CharField(choices=[('09.00 to 10.30', '09'), ('10.30 to 12.00', '1030'), ('12.00 to 01.30', '12'), ('02.00 to 03.30', '02'), ('03.30 to 05.00', '330'), ('Saturday', 'saturday')], max_length=20)),
                ('phone1', models.CharField(max_length=12, null=True)),
                ('phone2', models.CharField(max_length=12, null=True)),
                ('bsd', models.DateField(null=True)),
                ('staus', models.CharField(choices=[('doing', 'doing'), ('complete', 'complete'), ('break', 'break'), ('drop', 'drop')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.course')),
            ],
        ),
    ]
