# Generated by Django 3.2.18 on 2023-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='batchtime',
            field=models.CharField(choices=[('09', '09.00 to 10.30'), ('1030', '10.30 to 12.00'), ('12', '12.00 to 01.30'), ('02', '02.00 to 03.30'), ('330', '03.30 to 05.00'), ('saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='staus',
            field=models.CharField(choices=[('doing', 'Doing'), ('complete', 'Complete'), ('break', 'Break'), ('drop', 'Drop')], max_length=10),
        ),
    ]
