# Generated by Django 3.2.18 on 2023-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20230730_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bed',
            field=models.DateField(null=True),
        ),
    ]
