# Generated by Django 4.2.2 on 2023-08-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_student_bed_alter_student_phone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='batchtime',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fees',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
