# Generated by Django 3.2.18 on 2023-09-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batch', models.CharField(choices=[('09', '09.00 to 10.30'), ('1030', '10.30 to 12.00'), ('12', '12.00 to 01.30'), ('02', '02.00 to 03.30'), ('330', '03.30 to 05.00'), ('saturday', 'Saturday')], max_length=10)),
                ('pc', models.CharField(choices=[('pc1', 'PC1'), ('pc2', 'PC2'), ('pc3', 'PC3'), ('pc4', 'PC4'), ('pc5', 'PC5'), ('pc6', 'PC6'), ('pc7', 'PC7'), ('pc8', 'PC8'), ('pc9', 'PC9'), ('pc10', 'PC10'), ('pc11', 'PC11'), ('pc12', 'PC12'), ('pc13', 'PC13'), ('pc14', 'PC14'), ('pc15', 'PC15'), ('pc16', 'PC16'), ('pc17', 'PC17'), ('pc18', 'PC18'), ('pc19', 'PC19'), ('pc20', 'PC20'), ('pc21', 'PC21'), ('pc22', 'PC22'), ('pc23', 'PC23'), ('pc24', 'PC24'), ('pc25', 'PC25'), ('pc26', 'PC26'), ('pc27', 'PC27'), ('pc28', 'PC28'), ('pc29', 'PC29'), ('pc30', 'PC30')], max_length=10)),
                ('bsd', models.DateField(blank=True)),
                ('ebed', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('free', 'Free'), ('engage', 'Engage'), ('temparary', 'Temparary Free'), ('complaint', 'PC Complaint')], max_length=20)),
            ],
        ),
    ]
