# Generated by Django 3.2.18 on 2023-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systems',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('engage', 'Engage'), ('temparary', 'Temparary Free'), ('complaint', 'PC Complaint')], default='Free', max_length=20),
        ),
    ]
